# Generated by Django 6.0.2 on 2026-03-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order_shipping_address_order_shipping_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'approved'), ('PENDING', 'pending'), ('CANCELLED', 'rejected'), ('RETURNED', 'returned')], default='PENDING', max_length=50),
        ),
    ]
