# Generated by Django 6.0.2 on 2026-03-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='seller_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
