# Generated by Django 6.0.2 on 2026-02-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='is_verified',
        ),
    ]
