# Generated by Django 6.0.2 on 2026-02-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='doc',
            field=models.FileField(default='seller_documents/default.png', upload_to='seller_documents/'),
            preserve_default=False,
        ),
    ]
