# Generated by Django 6.0.2 on 2026-02-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_sellerprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
    ]
