# Generated by Django 6.0.2 on 2026-03-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_fix_duplicate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('PENDING', 'pending'), ('REJECTED', 'rejected')], default='PENDING', max_length=20),
        ),
    ]
